ExampleMod Solar Eruption Item PR
bluemagic123/tModLoader pull request #1329
Opened 2021-02-13 04:28 UTC by Pyroknight

### The changes to my PR for ExampleMod include an Example Solar Eruption type item, as well as the appropriate projectile and explosion projectile for it. I've commented and split it into concise lines of code for anyone to use so they may implement weapons like the Solar Eruption into their mod.

### These changes likely do not need any additional documentation, as I have already included several comments explaining everything about the item and its projectiles.

2021-02-13 04:30 UTC, RighteousRyan1 commented on ExampleMod/Projectiles/ExampleSolarEruptionProjectile.cs
> +				Dust dust1 = Dust.NewDustPerfect(chainHeadPosition, DustID.Smoke, new Vector2(0f, -1f).RotatedByRandom(MathHelper.ToRadians(360f)), 150, Color.White, 1.5f);
As with this, maybe change something like `dust1` to something... different?

2021-02-13 04:31 UTC, RighteousRyan1 commented on ExampleMod/Projectiles/ExampleSolarEruptionProjectile.cs
> +				Dust dust1 = Dust.NewDustPerfect(chainHeadPosition, DustID.Smoke, new Vector2(0f, -1f).RotatedByRandom(MathHelper.ToRadians(360f)), 150, Color.White, 1.5f);
Same with the others

2021-02-13 04:39 UTC, Steviegt6 requested changes

2021-02-13 04:39 UTC, Steviegt6 commented on ExampleMod/Projectiles/ExampleSolarEruptionExplosion.cs
> +			projectile.usesLocalNPCImmunity = true;
I feel like stuff such as this should have comments explaining what they actually do.

2021-02-13 04:39 UTC, Steviegt6 commented on ExampleMod/Projectiles/ExampleSolarEruptionExplosion.cs
> +            {
Formatting :trollface:

2021-02-13 04:39 UTC, Steviegt6 commented on ExampleMod/Projectiles/ExampleSolarEruptionExplosion.cs
> +					Dust dust1 = Dust.NewDustPerfect(projectile.Center, DustID.Smoke, new Vector2(0f, -speed * Main.rand.NextFloat(0.5f, 1.2f)).RotatedBy(MathHelper.ToRadians(360f / i * dusts + Main.rand.NextFloat(
Might help to comment explaining what the vector calculations are

2021-02-13 04:39 UTC, Steviegt6 commented on ExampleMod/Projectiles/ExampleSolarEruptionExplosion.cs
> +			projectile.localNPCImmunity[target.whoAmI] = 6;
Comments would help

2021-02-13 04:39 UTC, Steviegt6 commented on ExampleMod/Projectiles/ExampleSolarEruptionProjectile.cs
> +				Projectile explosion = Projectile.NewProjectileDirect(target.Center, Vector2.Zero, ModContent.ProjectileType<ExampleSolarEruptionExplosion>(), damage, 10f, projectile.owner, 0f, 1f);
I honestly find a lot of this hard to follow
Splitting it up into local vars with comments would likely help a new-comer

2021-02-13 04:39 UTC, Steviegt6 commented on ExampleMod/Projectiles/ExampleSolarEruptionProjectile.cs
> +			DelegateMethods.tilecut_0 = TileCuttingContext.AttackProjectile;
An explanation for this would be nice

2021-02-13 04:39 UTC, Steviegt6 commented on ExampleMod/Projectiles/ExampleSolarEruptionProjectile.cs
> +		public override bool PreDraw(SpriteBatch spriteBatch, Color lightColor)
Heavily lacking in comments

2021-02-13 04:43 UTC, RighteousRyan1 reviewed
Generally agreeing with Stevie, comments are needed in lots of spots and code is a bit messy. Maybe fix that up a bit then it should be good in my opinion.

2021-02-13 09:28 UTC, Pyroknight reviewed
Finished reviewing changes from Stevie and Ryan, made changes accordingly.

2021-02-13 21:23 UTC, Mellozx requested changes

2021-02-13 21:23 UTC, Mellozx commented on ExampleMod/Projectiles/ExampleSolarEruptionProjectile.cs
> +                    spriteBatch.Draw(texture, position - Main.screenPosition + yOffset, rectangle, Lighting.GetColor((int)position.X / 16, (int)position.Y / 16), rotation, new Vector2(rectangle.Width
Same as above

2021-02-13 21:23 UTC, Mellozx commented on ExampleMod/Projectiles/ExampleSolarEruptionProjectile.cs
> +            spriteBatch.Draw(texture, projectile.Center - Main.screenPosition + yOffset, rectangle, color, rotation, rectangle.Size() / 2f - Vector2.UnitY * 4f, projectile.scale, SpriteEffects.None,
A comment around the spritebatches would be nice, to clarify what you are doing

2021-02-13 21:23 UTC, Mellozx commented on ExampleMod/Projectiles/ExampleSolarEruptionProjectile.cs
> +                    spriteBatch.Draw(texture, position - Main.screenPosition + yOffset, rectangle, Lighting.GetColor((int)position.X / 16, (int)position.Y / 16), rotation, new Vector2(rectangle.Width
Also here

2021-02-13 21:23 UTC, Mellozx commented on ExampleMod/Projectiles/ExampleSolarEruptionProjectile.cs
> +            spriteBatch.Draw(texture, chainEnd - Main.screenPosition + yOffset, rectangle, Lighting.GetColor((int)chainEnd.X / 16, (int)chainEnd.Y / 16), rotation, texture.Frame().Top(), projectile.s
and here, since there isn't much clarification about what's being drawn

2021-02-13 21:53 UTC, Pyroknight reviewed
More fixes and indentation

2021-02-14 00:06 UTC, Pyroknight reviewed
Brace Indentation Fixes

2021-02-15 13:38 UTC, Mirsario commented
There is not much use in making PRs to 1.3 at this point, especially its ExampleMod. We're rebuilding EM in 1.4, and the quality standard is way higher than 1.3's. You should move this to a new PR targeting `1.4`. When you do that - it's a also good idea to make a branch with an unique name, like `1.4_solareruption`

2021-02-15 13:38 UTC, Mirsario requested changes
There is not much use in making PRs to 1.3 at this point, especially its ExampleMod. We're rebuilding EM in 1.4, and the quality standard is way higher than 1.3's. You should move this to a new PR targeting `1.4`. When you do that - it's a also good idea to make a branch with an unique name, like `1.4_solareruption`

2023-01-18 03:38 UTC, closed without merging