Fix extracted dll not being copied to references
bluemagic123/tModLoader pull request #1681
Opened 2021-08-02 23:33 UTC by Chik3r

### What is the bug?
#1677 
Extracted `.dll`s aren't copied to `references` because it doesn't expect dll files to be named `ModName.dll`

### How did you fix the bug?
Made the extractor know dll files can be named `ModName.dll`

### Are there alternatives to your fix?
Maybe

2021-08-03 00:06 UTC, saschahi commented
Hey, I'm the guy that created the issue.

just a heads up that in the pre-1.4 era the dlls would be extractes as modname_version.dll

for example: ProjectT_v0.5.5.dll

I'm not sure if that changed (I haven't dug into the 1.4 tModLoader source yet) but I just thought I should mention that since your fix doesn't seem to mention a version.

2021-08-03 00:59 UTC, JavidPack commented
This is probably fine, but we might be able to remove all the other options, and I'm not sure what our plans are for the references folder, since we aren't using it for the previous reasons anymore. I'll come back to this after we talk.

2021-08-06 09:52 UTC, Chicken-Bones commented
Lets get this done. Suggested path should be `Mod Sources/Mod Libraries`  or `mod_libraries` or something

2021-08-06 17:39 UTC, Steviegt6 requested changes

2021-08-06 17:39 UTC, Steviegt6 commented on patches/tModLoader/Terraria/ModLoader/UI/UIExtractMod.cs
> +					if (name == "All.dll" || PlatformUtilities.IsXNA ? name == "Windows.dll" || name == $"{mod.Name}.XNA.dll" : name == "Mono.dll" || name == $"{mod.Name}.FNA.dll" || name == $"{mod.Name}.dll") {
Can't we get rid of the `.FNA.dll` check now, too, since they're always FNA?

2021-08-06 17:40 UTC, Steviegt6 commented on patches/tModLoader/Terraria/ModLoader/UI/UIExtractMod.cs
> +					if (name == "All.dll" || PlatformUtilities.IsXNA ? name == "Windows.dll" || name == $"{mod.Name}.XNA.dll" : name == "Mono.dll" || name == $"{mod.Name}.FNA.dll" || name == $"{mod.Name}.dll") {
Oh, yeah, we can also get rid of the legacy `.dll` checks (`Windows.dll` and `Mono.dll`), as well as `.XNA.dll` files. I *believe* they've all been streamlined to `ModName.dll`.

2021-08-07 03:06 UTC, Chik3r commented
> Suggested path should be `Mod Sources/Mod Libraries`

Made it copy the dll to that folder now

> Oh, yeah, we can also get rid of the legacy `.dll` checks

Removed them, now only copies `ModName.dll`

2021-08-07 08:56 UTC, merged