[1.4] Ported RecipeHelper
bluemagic123/tModLoader pull request #1735
Opened 2021-08-13 15:01 UTC by ExterminatorX99

### What are the changes to ExampleMod?
Ported RecipeHelper

### Do these changes need additional documentation?

2021-08-13 15:12 UTC, Steviegt6 requested changes
Looks pretty good to me, though I feel like it could use some more examples that focus specifically on modded items and groups. I understand that this is a port of a previously-existing class from the original ExampleMod, but there's no reason to avoid improvement.

2021-08-13 15:12 UTC, Steviegt6 commented on ExampleMod/Content/ExampleRecipes.cs
> +			RecipeHelper.ExampleRecipeEditing(mod);
Would probably make more sense to make use of an `ILoadable`'s `Load()` or `ModSystem`'s `OnModLoad()` to do this.

2021-08-13 15:12 UTC, Steviegt6 commented on ExampleMod/Content/RecipeHelper.cs
> +				RecipeGroupID.IronBar // add a new recipe group, in this case the vanilla one for iron or lead bars.
May be worthwhile to explain how to retrieve modded group IDs?

2021-08-13 15:14 UTC, Steviegt6 commented on ExampleMod/Content/RecipeHelper.cs
> +		private static void MakeSimpleRecipe(Mod mod, string modIngredient, short resultType, int ingredientStack = 1, int resultStack = 1, string reqTile = null)
Ah, by the way: I believe we want to generally move away from using string to get instances of loaded types. We could use this method as an example of generics as well.

2021-08-13 15:53 UTC, Steviegt6 approved these changes
Looks good now, only thing I can say is that it may be cleaner to make an overload for tiles instead of just inputting a generic hen it isn't needed.

2021-08-23 16:48 UTC, Mirsario commented
> I'm not sure on what this file teaches people. It looks like a leftover from when locals were a must for creating recipes, and so the process was way more annoying.

2021-08-23 17:12 UTC, Steviegt6 commented
> > I'm not sure on what this file teaches people. It looks like a leftover from when locals were a must for creating recipes, and so the process was way more annoying.

That appears to be the case, but I feel like giving a couple examples of how to deal with recipe creation through slightly more unusual ways could prove beneficial to some people, even if it's an extreme minority. I suppose a merge isn't required but I do believe some could find this useful, even if they just use it to get a basic concept of how to deal with recipes.
Some methods in `RecipeHelper` are definitely less helpful than others, even as examples, though.

2022-04-28 21:19 UTC, closed without merging