Fix Modded Droplet Gores (resolves #2049)
bluemagic123/tModLoader pull request #2071
Opened 2022-01-04 06:58 UTC by Steviegt6

### What is the bug?
#2049

### How did you fix the bug?
Added a simple conditional for checking if the water style is that of a modded type, and instead use `GetDropletGore` instead of vanilla's hardcoded calculations.

### Are there alternatives to your fix?
No.

Resolves #2049.

2022-01-04 15:47 UTC, Mirsario requested changes

2022-01-04 15:47 UTC, Mirsario commented on patches/tModLoader/Terraria/GameContent/Drawing/TileDrawing.cs.patch
> + 			else if (Main.waterStyle > 1)
Code below overrides this.

2022-01-04 22:15 UTC, Steviegt6 commented on patches/tModLoader/Terraria/GameContent/Drawing/TileDrawing.cs.patch
> + 			else if (Main.waterStyle > 1)
When the CTRL+S doesn't work!

2022-01-06 12:38 UTC, Mirsario approved these changes

2022-01-06 12:39 UTC, merged