[1.4] Natively implement Large World Enabler
bluemagic123/tModLoader pull request #2079
Opened 2022-01-07 19:27 UTC by kittenchilly

Pretty self explanatory. Redone from the old PR for the new version and just including LWE.

2022-01-07 21:43 UTC, Mirsario requested changes

2022-01-07 21:43 UTC, Mirsario commented on patches/tModLoader/Terraria/WorldGen.cs.patch
> ++
Only allocate new arrays if the size is different.

2022-01-14 12:22 UTC, Mirsario requested changes

2022-01-14 12:22 UTC, Mirsario commented on patches/tModLoader/Terraria/WorldGen.cs.patch
> ++
Downsizing should also happen (without going lower than the default 8400x2400 size though.)
Loading a super large world for 1 second shouldn't permanently impact memory usage.

2026-01-27 17:48 UTC, kittenchilly commented
This is so old I'm just gonna close it.

2026-01-27 17:48 UTC, closed without merging