1.4 mod map layer
bluemagic123/tModLoader pull request #2098
Opened 2022-01-16 10:24 UTC by JavidPack

ModMapLayer allows usage of IMapLayer, which is how most icons are now drawn on the maps. Without ModMapLayer, the modder would have to manually unregister their layer, which is annoying. ModSystem.PreDrawMapIconOverlay can be used for hiding layers.

2022-01-16 11:43 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Map/IMapLayer.cs.patch
> ++		bool Visible { get; set; }
`internal set;` please

2022-01-16 11:43 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Map/IMapLayer.cs.patch
> ++		void Hide();
can have default impl, `=> Visible = false;`

2022-01-16 11:44 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Map/PingMapLayer.cs.patch
> ++
accidental whitespace patch

2022-01-16 11:44 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Map/MapIconOverlay.cs.patch
> ++				if(layer.Visible)
space after `if`

2022-01-22 23:32 UTC, Mirsario requested changes

2022-01-22 23:32 UTC, Mirsario commented on patches/tModLoader/Terraria/ModLoader/ModSystem.cs
> +		public virtual void PreDrawMapIconOverlay(List<IMapLayer> layers, MapOverlayDrawContext mapOverlayDrawContext) { }
Sounds like this list has no reason to not be readonly. Also, shouldn't "Overlay" be plural?

2022-01-22 23:32 UTC, Mirsario commented on ExampleMod/Common/Systems/ExampleMapLayer.cs
> +	public class ExampleMapLayer : ModMapLayer
I think I'd rather have this in just Common than in Systems

2022-01-23 10:19 UTC, Mirsario approved these changes

2022-01-23 11:56 UTC, Chicken-Bones approved these changes

2022-01-23 20:57 UTC, merged