[1.4] CanStack & prefix weapon stacking
bluemagic123/tModLoader pull request #2127
Opened 2022-01-31 13:25 UTC by direwolf420

### Description
This PR attempts to tackle several things:
1. Prevent stackable weapons that are prefixed from being stacked together in most relevant contexts (does not include accessories, ammo, coins etc)
2. Introduce a generic `CanStack` hook in all contexts where item stack manipulation between two items take place
3. Clarify usage of several `Item` methods: `IsTheSameAs` -> `IsSameTypeAs`. `IsNotTheSameAs` -> `internal`

First iteration of this PR will be a draft that implements (1.).

2022-02-12 11:36 UTC, Chicken-Bones approved these changes

2022-02-16 11:56 UTC, Mirsario requested changes
Code looks good, just nitpicks:

2022-02-16 11:56 UTC, Mirsario commented on patches/tModLoader/Terraria/Item.TML.cs
> +		public bool allowReforgeForStackableItem = false;
Change to an autoproperty, public fields are not to appear in classes in APIs.
```cs
		public bool AllowReforgeForStackableItem { get; set; }
```

2022-02-16 11:56 UTC, Mirsario commented on patches/tModLoader/Terraria/ModLoader/ModItem.cs
> +		/// </summary>
This is how breaks are supposed to be used.. Can you apply to this to the rest?
```suggestion
		/// Allows you to decide if this item is allowed to stack with another of its type.
		/// <br/>This is only called when attempting to stack with an item of the same type.
		/// <br/>This is usually not called for coins and ammo in the inventory/UI.
		/// <br/>This covers all scenarios, if you just need to change in-world stacking behavior, use <see cref="CanStackInWorld"/>
		/// </summary>
```

2022-02-16 18:51 UTC, Mirsario approved these changes

2022-02-17 11:21 UTC, merged