Fixed a vanilla bug with OGG audio track looping.
bluemagic123/tModLoader pull request #2294
Opened 2022-04-15 22:26 UTC by JamzOhJamz

### What is the bug?

Terraria 1.4 does not correctly implement the parsing/reading of .OGG file meta tags. Using music with loop points is impossible as long as this bug remains unfixed, which is undesirable.

### How did you fix the bug?

I changed one line in `OGGAudioTrack` to ensure meta tags are parsed correctly.

### Are there alternatives to your fix?

I've heard there's an instance of obsolete code inside of the `OGGAudioTrack` class, and changing it gives you the values directly without requiring any modification to the `TryGettingVariable` method. This fix, however, is the only one that managed to fix the problem.

2022-04-15 22:42 UTC, Mirsario commented on patches/tModLoader/Terraria/Audio/OGGAudioTrack.cs.patch
> ++			if (vorbisComment.StartsWith(variableWeLookFor) && int.TryParse(vorbisComment.Remove(0, variableWeLookFor.Length + 1), out int result))
```suggestion
-			if (vorbisComment.StartsWith(variableWeLookFor) && int.TryParse(vorbisComment, out int result))
+			if (vorbisComment.StartsWith(variableWeLookFor) && int.TryParse(vorbisComment.Substring(variableWeLookFor.Length), out int result))
```

2022-04-15 22:48 UTC, Mirsario requested changes

2022-04-15 22:48 UTC, Mirsario commented on patches/tModLoader/Terraria/Audio/OGGAudioTrack.cs.patch
> ++			if (vorbisComment.StartsWith(variableWeLookFor) && int.TryParse(vorbisComment.Remove(0, variableWeLookFor.Length + 1), out int result))
Looks like this can technically throw ArgumentOutOfRangeException. Also, replace the Remove with a Substring call.

2022-04-15 22:56 UTC, Mirsario commented on patches/tModLoader/Terraria/Audio/OGGAudioTrack.cs.patch
> ++			if (vorbisComment.StartsWith(variableWeLookFor) && int.TryParse(vorbisComment.Remove(0, variableWeLookFor.Length + 1), out int result))
*

2022-04-16 14:53 UTC, JamzOhJamz commented
I’m sorry, I am new to Git pull requests. What do I have to do, or did you fix the solution yourself already?

2022-04-16 17:09 UTC, Mirsario approved these changes
Improved & tested everything now, thanks. Apparently VorbisReader.Comments is legacy, there was a warning suggesting .Tags.All instead, which is an easier to use dictionary.

In the future, if you'll be making any new PRs, I suggest you to create separate branches for them, like `1.4_ogg_loop_points` as an example for this one. Makes things a bit easier both for you and everyone else.

2022-04-16 17:15 UTC, merged