1.4.4.7: Recipe shimmer examples and fixes
bluemagic123/tModLoader pull request #3086
Opened 2022-11-08 22:44 UTC by JavidPack

2022-11-08 23:01 UTC, Chicken-Bones requested changes

2022-11-08 23:01 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Recipe.cs.patch
> ++			ItemID.Sets.IsAMaterial[5325] = false;
Why do we have to add these? Can you comment where they come from in the vanilla source? Maybe make a patch note there that links back to here?

Can mods replicate this?

2022-11-08 23:01 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Recipe.TML.cs
> +		}
Hmm, these probably shouldn't have parameters. Maybe just `NotDecraftable()`, `CrimsonOnly()`, `CorruptionOnly()`? Perhaps `DisableShimmer()` to match `AddCustomShimmerResult`?

I feel like it would be better to have some sort of condition/category system to replace the `crimson/corruption` sets with. Since it's not really clear what these do.

Maybe something like `AddShimmerCondition`?

2022-11-08 23:01 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Item.cs.patch
> ++				bool flag = recipe.requiredItem.Count > 1 && recipe.requiredItem[1].stack > 0;
I think just `recipe.requiredItem.Count > 1` is correct here. This flag looks to be checking for multiple ingredients.

2022-11-08 23:01 UTC, Chicken-Bones commented on ExampleMod/Content/Items/Weapons/ExampleFlail.cs
> +				.SetDecraftable(false)
I'd rather we have separate examples for everything shimmer/decraftable related.

2022-11-10 18:02 UTC, JavidPack commented on patches/tModLoader/Terraria/Recipe.cs.patch
> ++			ItemID.Sets.IsAMaterial[5325] = false;
Added comments. Modders can use PostSetupRecipes to change these.

2022-11-21 20:01 UTC, merged