IL Editing QoL Stuff
bluemagic123/tModLoader pull request #3252
Opened 2023-02-13 07:19 UTC by Destructor-Ben

https://github.com/tModLoader/tModLoader/issues/3213

Added 3 methods
`DumpILHooks()` will dump the list of currently registered IL hooks to the console (useful for reflection)
`DumpOnHooks()` will do the same but for detours
`LogILPatchFailure(Mod mod, ILContext il, string reason)` is a method for logging to the console that an IL patch has failed (this is for standardization but is less important)

This PR may also include helper functions for dumping IL to files and diffing them if this doesn't happen:
https://github.com/tModLoader/tModLoader/issues/3213#issuecomment-1421833910

2023-02-27 07:02 UTC, Chicken-Bones requested changes

2023-02-27 07:02 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/MonoModHooks.cs
> +		mod.Logger.Warn($"Failed to IL edit method \"{il.Method.Name}\", because \"{reason}\"");
Could dump the entire `il.ToString` to a text file somewhere (`Logs/ILDumps`) while you're at it maybe?

2023-02-27 07:02 UTC, Chicken-Bones commented on ExampleMod/Content/Items/Accessories/WaspNest.cs
> +				MonoModHooks.LogILPatchFailure(ModContent.GetInstance<ExampleMod>(), il, "Unable to locate 566 on the stack");
Hm... I think that having to make error messages for every try-get which can fail will annoy some people, and that a better approach would be to wrap the entire method in a `try catch` and do a `throw new Exception("msg")`

Exceptions have the benefit of giving exact line numbers too

2023-02-27 07:02 UTC, Chicken-Bones commented on ExampleMod/Content/Items/Accessories/WaspNest.cs
> +				MonoModHooks.LogILPatchFailure(ModContent.GetInstance<ExampleMod>(), il, "Unable to locate 566 on the stack");
Can call `LogILPatchFailure` in the `catch` handler

2023-02-28 02:47 UTC, Destructor-Ben commented on patches/tModLoader/Terraria/ModLoader/MonoModHooks.cs
> +		mod.Logger.Warn($"Failed to IL edit method \"{il.Method.Name}\", because \"{reason}\"");
Should I also add methods the methods for dumping IL and diffing it, or will that be done in MonoMod?

2023-03-02 04:38 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/MonoModHooks.cs
> +		mod.Logger.Warn($"Failed to IL edit method \"{il.Method.Name}\", because \"{reason}\"");
dumping sure. Diffing is best left to the user's preferred tools

2023-03-27 01:11 UTC, merged

2023-03-27 01:16 UTC, Chicken-Bones commented on ExampleMod/Content/Items/Accessories/WaspNest.cs
> +			}
It appears I may have been too hasty. Do we want to throw here? Or just log and dump?
The exception doesn't actually log.