Migrate users to 1.4.3-legacy in preparation for 1.4.4 default
bluemagic123/tModLoader pull request #3545
Opened 2023-06-13 21:15 UTC by JavidPack

Still a lot todo...

2023-06-14 00:02 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/ModLoader.cs
> +		public static bool SeenMigrateTo143BranchMessage;
We want to show it on _every_ launch for people who aren't on the branch. GoG players don't matter, but you should use the result from `SteamApps.GetCurrentBetaName` to control the visibility of the message

2023-07-04 18:18 UTC, Solxanich requested changes
A few changes to simplify some items

2023-07-04 18:18 UTC, Solxanich commented on patches/tModLoader/Terraria/ModLoader/UI/Interface.cs
> +				return false;
Use case?
We want all 1.4.3 users, independent of if they installed via default branch on steam or manually to use 1.4.3-legacy builds going forward.
Especially since it involves save files.
Would recommend we instead check if the tML version is greater than 2022.09.47.62 and return false

2023-07-04 18:18 UTC, Solxanich commented on patches/tModLoader/Terraria/ModLoader/Core/ModOrganizer.cs
>  			Version tmodVersion = new Version(BuildInfo.tMLVersion.Major, BuildInfo.tMLVersion.Minor);
This logic should probably be rewritten and refactored with the CleanupPublishFolder logic.

Specs on this function:
- tml version 0.12 is a direct file path to .tmod (no folder). Is a legacy case
- for purposes of mod loading, we want the latest .tmod for the tml version running
- if there is no .tmod for this version or earlier, we return null (ie no mod exists that can be loaded). Should be logged

2023-07-04 18:18 UTC, Solxanich commented on patches/tModLoader/Terraria/ModLoader/UI/UIModItem.cs
> +				if (BuildInfo.IsStable && new Version(_mod.tModLoaderVersion.Major, _mod.tModLoaderVersion.Minor) == new Version(BuildInfo.tMLVersion.Major + (lastMonth ? 1 : 0), BuildInfo.tMLVersion.Minor + (la
use `> BuildInfo.StableVersion`

2023-07-04 23:53 UTC, Solxanich approved these changes

2023-07-05 20:26 UTC, merged