Added ExampleUseStyleWeapon
bluemagic123/tModLoader pull request #3760
Opened 2023-08-25 21:11 UTC by Stardust9681

### What are the changes to ExampleMod?
Added ExampleUseStyleWeapon, showcasing an implementation of `ModItem.UseStyle(Player, Rectangle)` and `ModItem.UseItemHitbox(Player, Rectangle&, bool&)`.
### Do these changes need additional documentation?
Unlikely.

2025-08-07 07:44 UTC, Chicken-Bones approved these changes

2025-08-07 07:44 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/ItemLoader.cs
> +	public static int UseStyleCount { get; private set; } = ItemUseStyleID.RaiseLamp + 1;
I'd rather see a `Count` field added to `ItemUseStyleID`. It's more correct and we're more likely to pick it up in patch reviewer.

2025-08-07 07:44 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ID/ContentSamples.cs.patch
> ++			if (item.useStyle != 0) // #3760 - Allow negative useStyle values since all the other useStyle checks allow it
Upstreamed, and fixed some incoming 1.4.5 checks :)

2025-08-07 07:44 UTC, Chicken-Bones commented on ExampleMod/Content/Items/Weapons/ExampleCustomUseStyleWeapon.cs
> +		public static Dictionary<int, int> HandOffsets; // Stores custom hold offsets if needed
`CreateIntSet` please

2025-08-07 07:44 UTC, Chicken-Bones commented on ExampleMod/Content/Items/Weapons/ExampleCustomUseStyleWeapon.cs
> +			hitbox = new Rectangle(X1, Y1, X2 - X1, Y2 - Y1);
This is kinda sad, would be nice if we had `Utils.CornerRect`, or `BoundingRect(p1, p2)`

In 1.4.5 I do it like this:
```cs
			var r = Utils.CenteredRectangle(points[0], Vector2.Zero);
			foreach (var point in points)
				r = r.Including(point.ToPoint());

			BoundingRect = r;
```
			
Where `Including` is an extension method in `Utils`
```cs
		public static Rectangle Including(this Rectangle rect, Point point)
		{
			int l = Math.Min(rect.Left, point.X);
			int r = Math.Max(rect.Right, point.X);
			int t = Math.Min(rect.Top, point.Y);
			int b = Math.Max(rect.Bottom, point.Y);
			return new Rectangle(l, t, r - l, b - t);
		}
```

2025-08-07 19:53 UTC, JavidPack commented on ExampleMod/Content/Items/Weapons/ExampleCustomUseStyleWeapon.cs
> +			hitbox = new Rectangle(X1, Y1, X2 - X1, Y2 - Y1);
Added.

2025-08-08 03:01 UTC, Chicken-Bones requested changes

2025-08-08 03:01 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Utils.TML.cs
> +	public static Rectangle BoundingRectangle(params Vector2[] vectors) => BoundingRectangle(vectors.Select(ToPoint).ToArray());
Since we don't have a value linq system imported, I recommend duplicating the method above

2025-08-08 03:01 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Utils.TML.cs
> +	public static Rectangle BoundingRectangle(params Point[] points)
I'm not happy making this `params` until we have `params Span`

2025-08-08 03:01 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Utils.TML.cs
> +		foreach (var point in points)
A regular for-i loop could start at 1

2025-08-13 00:00 UTC, Chicken-Bones approved these changes

2025-08-19 22:11 UTC, merged

2025-08-21 12:56 UTC, direwolf420 commented on ExampleMod/Content/Items/Weapons/ExampleCustomUseStyleWeapon.cs
> +			//ExampleCustomUseStyleItemSets.HandOffsets[Type] = 0;
Shouldn't this be in SetStaticDefaults instead?

2025-08-21 12:56 UTC, direwolf420 commented on ExampleMod/Content/Items/Weapons/ExampleCustomUseStyleWeapon.cs
> +				//ExampleCustomUseStyleItemSets.HandOffsets[item.type] = -6; // Alternate approach to setting HandOffsets
Same here

2025-08-21 18:40 UTC, JavidPack commented on ExampleMod/Content/Items/Weapons/ExampleCustomUseStyleWeapon.cs
> +			//ExampleCustomUseStyleItemSets.HandOffsets[Type] = 0;
K.

2025-08-21 18:40 UTC, JavidPack commented on ExampleMod/Content/Items/Weapons/ExampleCustomUseStyleWeapon.cs
> +				//ExampleCustomUseStyleItemSets.HandOffsets[item.type] = -6; // Alternate approach to setting HandOffsets
K.