tModLoader.CodeAssist overhaul
bluemagic123/tModLoader pull request #3839
Opened 2023-09-25 02:16 UTC by BasicallyIAmFox

### What is the new feature?
Reworked analyzers for tML.
- Renamed tModLoader.CodeAssist to tModCodeAssist to fit with the tML branding
- Moved tModCodeAssist to the tML repository and added it as an for mods analyzer in `tModLoader.targets`
- Ported the old analyzer rules
- Added new rules

Current list of analyzer rules:
- Magic numbers to IDs
- Detect and hint that `Item.ResearchUnlockCount = 1` is default behaviour.

### Why should this be part of tModLoader?
Having tModCodeAssist in the tModLoader repository is much better than having it separately and publishing it as a nuget package because we don't have to consider supporting 1.3, 1.4.3, and 1.4.4 at the same time in one codebase. New analyzer rules will also help new modders port vanilla code and can help them simplify their own code.

### Are there alternative designs?
- Leaving the name as tModLoader.CodeAssist (bad)
- Leaving the analyzer in a separate repository and making tML a submodule of it (bad)
- Leaving the analyzer as a nuget package (bad)

### Sample usage for the new feature
![image](https://github.com/tModLoader/tModLoader/assets/65787578/d76eaca7-7b58-4195-b1af-8c22b5a8e79f)
![image](https://github.com/tModLoader/tModLoader/assets/65787578/f1dff7e0-5234-4596-b7cb-e0f996e763d4)

### ExampleMod updates
N/A

### TODO
* [ ] Port `rand` simplify rule

2023-09-25 16:12 UTC, steviegt6 commented
Points of concern:
- I believe some mods are evil and actually extend the `ai` arrays to allow for additional values,
- there are valid reasons for mods to want to "reset" the research count to 1 (i.e. tweaking another mod).

I understand that analyzers can be configured, and I'm perfectly fine with the former point being a configurable warning (certainly should not be an error though).

The latter should always be a hint (which is how it appears to be based on the screenshot), but I want to establish this as a standard. Changing/resetting research counts is very reasonable mod behavior unlike extending the length of the `ai` array, so I'd like to make sure we leave these suggestions as easily-ignorable hints.

Just my two cents.

2023-09-25 16:18 UTC, steviegt6 commented
Took a glance at the content of the PR and:
1. might it be better to shove annotations and IdDictionary instances in a TML partial class for IDs,
2. and what it make more sense to do tML annotations through an XML file or something instead of manually patching each field and class?

For 2), it just reduces patch quantity and sizes, but may also make it easier to keep tML up-to-date. Introducing this infrastructure can make it easier to annotate dependent mods or other external dependencies if they aren't annotated.

2023-09-25 16:38 UTC, BasicallyIAmFox commented
> Took a glance at the content of the PR and:
> 
>     1. might it be better to shove annotations and IdDictionary instances in a TML partial class for IDs,
> 
>     2. and would it make more sense to do tML annotations through an XML file or something instead of manually patching each field and class?
> 
> 
> For 2), it just reduces patch quantity and sizes, but may also make it easier to keep tML up-to-date. Introducing this infrastructure can make it easier to annotate dependent mods or other external dependencies if they aren't annotated.

1) will do but later. Not major priority atm.
As for 2), it sounds interesting, but I have no clue how to do it, unfortunately.

2023-09-25 16:44 UTC, BasicallyIAmFox commented
> Points of concern:
> 
>     * I believe some mods are evil and actually extend the `ai` arrays to allow for additional values,
> 
>     * there are valid reasons for mods to want to "reset" the research count to 1 (i.e. tweaking another mod).
> 
> 
> I understand that analyzers can be configured, and I'm perfectly fine with the former point being a configurable warning (certainly should not be an error though).
> 
> The latter should always be a hint (which is how it appears to be based on the screenshot), but I want to establish this as a standard. Changing/resetting research counts is very reasonable mod behavior unlike extending the length of the `ai` array, so I'd like to make sure we leave these suggestions as easily-ignorable hints.
> 
> Just my two cents.

I haven't seen any mod that modifies research count. Could you point me any examples of mods doing that?

2024-03-07 17:13 UTC, Mirsario requested changes

2024-03-07 17:13 UTC, Mirsario commented on tModCodeAssist/tModCodeAssist.sln
> +EndProject
Is there a single point in offering a VS extension nowadays? I don't see one.

2024-03-07 17:13 UTC, Mirsario commented on tModCodeAssist/tModCodeAssist.CodeFixes/tModCodeAssist.CodeFixes.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
Most of our `.csproj` and `.targets` files use tabs nowadays.

2024-03-07 17:13 UTC, Mirsario commented on patches/tModLoader/Terraria/release_extras/tMLMod.targets
>  		<tMLName>tModLoader</tMLName>
No need for a new folder, output analyzers into `Libraries`, the way `tModPorter` and `tModLoader.BuildTasks` get put there:
![image](https://github.com/tModLoader/tModLoader/assets/6795251/7d224d6d-d18a-47b3-8cfd-663f556e64c4)

2024-03-07 17:13 UTC, Mirsario commented on patches/tModLoader/Terraria/ID/AnimationID.TML.cs
> +partial class AnimationID
Why are these preprocessor conditionals required?

2024-03-08 15:47 UTC, closed without merging

2024-03-08 15:56 UTC, BasicallyIAmFox commented
how do i reopen this lmao

2024-03-10 16:18 UTC, Mirsario commented
Recreate the PR and stop rewriting history so much. We squash PRs, so you don't need an overly clean history in PRs.

2024-03-10 16:20 UTC, Mirsario commented
.

2024-03-10 21:55 UTC, BasicallyIAmFox commented
> Recreate the PR and stop rewriting history so much. We squash PRs, so you don't need an overly clean history in PRs.

wtf you mean "recreate the pr"? i wanted to rewrite the pr from scratch either way