Refactored mod creation to use a file tree of templates.
bluemagic123/tModLoader pull request #4134
Opened 2024-03-24 22:30 UTC by Mirsario

To assist two+ active PRs (#2472 and #4037), this one does the following:
- [x] Moves code related to creating & upgrading mod source folders out of UI and into a new separate `Terraria.ModLoader.Core.SourceManagement` class.
- [x] Replaces textfile-generating hardcode with a filetree of embedded resources that are enumerated and exported to populate mod src folders. The embedded resources use the [Mustache](https://mustache.github.io/mustache.5.html) logicless template format in their names and contents (this concept will be nice to use for mod descriptions too in userland in the future). Optional files, such as the BasicSword, are skipped by making their filenames evaluate to nothing. 
- [ ] Removes `TargetFramework` and `PlatformTarget` from default `.csproj` files, putting it into `tModLoader.targets` instead.
- [ ] Makes Csproj upgrades attempt to function via XML edits, if they're not too broken.

Additionally:
- Slightly improves all template files.
- As too many people don't bother even providing a mod icon, I felt like updating the default mod icon to be slightly more presentable, while communicating its placeholder nature:
![](https://github.com/tModLoader/tModLoader/raw/b071122ded823caf366cfd7a1f812fb0863ceba5/patches/tModLoader/Terraria/ModLoader/Default/iconTemplate.png) -> ![](https://github.com/tModLoader/tModLoader/raw/e3c9da7010c525931bec837a96f7d8c69d2bbea4/patches/tModLoader/Terraria/ModLoader/Templates/icon.png)

2024-03-25 19:25 UTC, Destructor-Ben commented
In a future PR could we allow specifying our own template? atm I copy paste a template and hope I remembered to change all file names + contents of files

2024-03-25 20:30 UTC, JavidPack commented
Should we move LangVersion to the tMLMod.targets too? I believe a modder should still be able to override it in their mod's csproj, but an issue we have right now is that modders are seeing suggestions in VS for language versions that the ingame complier does not support. I know there is a pr for doing it through dotnet itself, but even then we'd want to make sure that only the highest supported lang version is the default.

2024-03-26 00:12 UTC, Mirsario commented
> Should we move LangVersion to the tMLMod.targets too?

I've done that now, with it explicitly set to `10.0` for now. But only overrides with old versions in values will be auto-removed in the upgrade process. `latest`, `preview`, and >=`11.0` will be kept, so I guess it's not really helping what you've described. Oh well, hopefully we merge 2472 soon.

2024-03-26 00:18 UTC, JavidPack commented
Will this be able to easily remove `<PackageReference Include="tModLoader.CodeAssist" Version="0.1.*" />` once #4099 is merged? I haven't parsed all the code yet, just curious.

2024-03-26 00:50 UTC, Mirsario commented
Yes, here's the code to insert even:
```cs
var items = root.Elements().Where(e => e.Name.LocalName == "ItemGroup").SelectMany(g => g.Elements());

// Remove the old analyzer package.
nodesToRemove.AddRange(items.Where(
	e => e.Name.LocalName == "PackageReference" && e.Attribute("Include")?.Value == "tModLoader.CodeAssist"
));
```

2024-04-02 19:57 UTC, Chicken-Bones requested changes
Overall this is an excellent change. I've provided some factoring feedback.

This PR should _not_ change the templates. It makes it really hard to review. Please split template changes into an additional 1 or 2 PRs (2 if there are changes that have to be done both before and after this PR).

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Assets/AssemblyResourcesContentSource.cs
> +			resourceNames = resourceNames.Where(p => !p.StartsWith(startingPath));
Is this necessary? You're not using the asset system for your templates anymore

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Templates/Properties/launchSettings.json
> +		}
Why would the average user want these two configurations?

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Templates/Properties/launchSettings.json
> +			"executablePath": "dotnet",
Don't these need to use `$(DotNetName)`?

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Templates/{{ModName}}.csproj
> +		<LangVersion>latest</LangVersion>
Remove?

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Templates/{{ModName}}.csproj
> +		<PackageReference Include="tModLoader.CodeAssist" Version="0.1.*" />
Does this not belong in `tMLMod.targets` too?

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Terraria.csproj.patch
> ++		<EmbeddedResource Include="ModLoader/Templates/**">
You can use `Update=` instead of `Remove` and then `Include`

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Templates/{{ModName}}.cs
> +namespace {{ModName}};
Needs approval from @JavidPack are we doing file scoped namespaces now? We don't in ExampleMod

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/SourceManagement.cs
> +		object boxedParameters = templateParameters;
why use record struct and boxing, rather than regular `record`

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/SourceManagement.cs
> +		}
This needs to be a modification itself. 
I also prefer `modifications.Any()`

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/SourceManagement.cs
> +			return false;
this is currently the only way to get `FileBroken`. See my above comment about factoring this out, so this method doesn't need a `bool` return, and can just return (or `yield`) the list of modifications instead

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/SourceManagement.cs
> +		}
I feel like the `status` enum here is not particularly needed or readable. 

```cs
if (File.Exists(csprojPath)
      && TryLoadXmlDocument(csprojPath, LoadOptions.PreserveWhitespace, out var document)
      && IsModernCsproj(document)) {
    
    var modifications = CollectCsprojUpgradeActions(document);
    if (modifications.Count == 0)
        return false;

    action = () => {
        modifications!.ForEach(m => m());
        WriteXmlDocumentToFile(csprojPath, document!);
    }
    return true;
}

action = () => ResetCsprojFile(csprojPath, templateParameters);
return true;
```

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/SourceManagement.cs
> +					ResetCsprojFile(csprojPath, createBackup: status is not UpgradeStatus.FileMissing, templateParameters);
No need for the `createBackup` parameter, just make a backup inside the function if the file exists

2024-04-02 19:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/SourceManagement.cs
> +		}
Normally I'd factor this as a local function at the top of the method, like:
```cs
void RemoveNodes(IEnumerable<XNode> nodes) {
    modifications.Add(() => ...)
}
```

2024-04-09 11:42 UTC, Mirsario commented on patches/tModLoader/Terraria/ModLoader/Assets/AssemblyResourcesContentSource.cs
> +			resourceNames = resourceNames.Where(p => !p.StartsWith(startingPath));
Duplicate extension errors are thrown at ContentSource initialization time, not access time. Any duplicate extensions found in EmbeddedResources will crash the game. This behavior seriously needs redesigns, as we still have crashes from some resourcepacks intended for vanilla.

2024-04-09 11:47 UTC, Mirsario commented on patches/tModLoader/Terraria/ModLoader/Templates/Properties/launchSettings.json
> +		}
I guess it'll cause more confusion than it's worth, will remove.

2024-04-09 12:13 UTC, Mirsario commented on patches/tModLoader/Terraria/ModLoader/Core/SourceManagement.cs
> +		}
A CA rule cries about .Any() being inferior. csharpbad.

2024-04-10 23:11 UTC, merged