Finish implementing deleting unloaded tiles feature, add VanillaFallbackOnModDeletion examples
bluemagic123/tModLoader pull request #4325
Opened 2024-07-30 20:41 UTC by JavidPack

When a user decides to disable a mod, that mod will leave unloaded tiles in the world. If the user wishes to permanently remove a mod, then the tiles are a nuisance. The code exists to do this, replacing those tiles with `VanillaFallbackOnModDeletion`, but the code currently will not run because it is not hooked up to any UI for the user to click.

This PR also will add proper `VanillaFallbackOnModDeletion` usage and also update the documentation to warn about how to correctly use `VanillaFallbackOnModDeletion`.

TODO:
- [ ] Do we also need to remove items from chests? Modded storages? Inventories?
- [ ] How should this effect be triggered? It's a rare desire, so we don't want users to accidentally press it or be confused by it. If we can't decide on a UI, a hidden keypress like holding shift can trigger this and we can just mention this to anyone who asks.

# Example
In this example several tiles are replaced with suitable alternatives via `VanillaFallbackOnModDeletion` usage. ExampleTorch (bottom middle, near the player) shows the default behavior of turning back to dirt. ExampleWallAdvanced shows the default wall behavior, turning to air. ExampleChair, Chest, Block, Sign, Platform, Ore, Bar all revert to a vanilla tile in this example. On the left is TileObjectDataShowcase, which uses different FrameX and FrameY values from a normal 2x2 tile. This shows how a modded might make a mistake if they use `VanillaFallbackOnModDeletion` on a `tileframeimportant` tile that does not exactly match the layout of the vanilla tile they intend to fallback to.

**Before:**
![2024-07-30_12-36-07](https://github.com/user-attachments/assets/ff2307a2-d379-44c6-9821-4c7801d336a6)

**Unloaded:**
![2024-07-30_12-35-02](https://github.com/user-attachments/assets/0d9dab18-22e0-4d19-843b-b043a1f384c3)

**Deleted and replaced:**
![2024-07-30_12-39-50](https://github.com/user-attachments/assets/9887d902-92f9-4abd-abde-a82724d09b5c)

2024-07-30 23:50 UTC, Chicken-Bones commented
Removing items from storages would be a good option to provide, but isn't needed in the base implementation. Items are much easier for the player to manage themselves.

2024-08-08 00:57 UTC, Solxanich commented
As far as modded chest to regular chest goes, 
If my memory serves the contents are preserved if it goes from a chest to a different chest. It's why unloaded chest works.

An alternative question is if the VanillaFallback type needs to default that modded chests fallback to wooden chests?

2024-08-08 19:49 UTC, JavidPack commented
We could do wooden chests specifically, or try to have all tiles default to style 0, but that might be hard to implement. The fallback feature is a really rare situation and I don't want every mod with content thinking they need to spend multiple lines declaring a fallback tile and tile style for all modtile. 

I think keeping it simple is fine, if someone ends up with a locked golden chest, I think that might be better than a selection of different chest style all turning into the same wooden chest. That said, most mods don't even use tile styles so most will be wooden chests anyway.

2025-04-03 00:01 UTC, JavidPack commented
New logging:

```
[18:00:19.209] [.NET TP Worker/INFO] [Terraria]: Loading World: 1313, IsCloud=True, Width: 4200, Height: 1200, Evil: 1, GameMode: 1
[18:00:19.266] [.NET TP Worker/INFO] [StatusText]: Loading world data
[18:00:21.553] [.NET TP Worker/INFO] [tML]: Unloaded tiles and walls have been purged from this world using the Ctrl-Alt-Shift shortcut while selecting the world. If this was unintentional please restore to a backup.
[18:00:23.098] [.NET TP Worker/INFO] [tML]: Purged tiles: ExampleMod/BasicTileEntityTile, ExampleMod/EnemyBanner, ExampleMod/Example1x1RubbleNatural, ExampleMod/ExampleAnimatedTile, ExampleMod/ExampleBar, ExampleMod/ExampleBlock, ExampleMod/ExampleCampfire, ExampleMod/ExampleCritterCage, ExampleMod/ExampleCustomFramingTile, ExampleMod/ExampleLamp, ExampleMod/ExampleMusicBoxTile, ExampleMod/ExampleOre, ExampleMod/ExampleSand, ExampleMod/ExampleStatue, ExampleMod/ExampleTorch, ExampleMod/ExampleTrap, ExampleMod/ExampleChandelier, ExampleMod/ExampleChest, ExampleMod/ExampleDoorClosed, ExampleMod/ExampleDoorOpen, ExampleMod/ExampleDresser, ExampleMod/ExamplePlatform, ExampleMod/ExampleTable, ExampleMod/ExampleWideBannerTile, ExampleMod/MinionBossRelic
[18:00:24.108] [.NET TP Worker/INFO] [tML]: Purged walls: ExampleMod/CrimsonFossilWall, ExampleMod/ExampleWall, ExampleMod/ExampleWallAdvanced
```

2025-04-03 00:07 UTC, JavidPack commented
I couldn't come up with any UI change I'd want to make to the UIWorldSelect that would look good or be sensible, so I figured we might as well merge the feature and just let people in support ever know if they need it. We can do a UI later.

Another option is a chat command in-game, but I don't think we should fill up the /help output more than we need to.

2025-04-03 08:07 UTC, direwolf420 commented
Not a big fan of ctrl-alt-shift combination. These are all common "modifier" keys used in alot of programs. By themselves they shouldn't cause an action this severe, it should be coupled with some other key, maybe U for "unloaded"

2025-04-03 08:10 UTC, JavidPack commented
Yeah, we decided it'll be moving it to a chat command instead.

2025-04-03 20:28 UTC, JavidPack commented
Here is the new command in action.

https://github.com/user-attachments/assets/dadb9c5a-5283-4cac-ac19-2f61f835fb38

2025-05-14 01:46 UTC, Chicken-Bones requested changes

2025-05-14 01:46 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/PurgeUnloadedCommand.cs
> +				if (purgeTiles && t.HasTile && t.TileType >= TileID.Count && unloadedTileTypes.Contains(t.TileType)) {
This will be faster if you use an array than a `HashSet`, No need for the `t.TileType >=` check then either

2025-05-14 01:46 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/PurgeUnloadedCommand.cs
> +		List<Point16> coordinates = [];
This _could_ OOM. You can call `Main.sectionManager.SetAllSectionsLoaded()` instead to reset the section framed cache to the freshly loaded state, then sections will re-frame when they come in view as normal.

2025-05-14 01:46 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/IO/TileIO_Basic.cs
> +	internal static bool canPurgeOldData => false; //for deleting unloaded mod data in a save during loading; should point to UI flag; temp false; The /purgeunloaded chat command is the current approach
Lets remove this :)

2025-05-15 19:53 UTC, direwolf420 commented on patches/tModLoader/Terraria/ModLoader/ModBlockType.cs
> +	/// <br/><br/> <see cref="Main.tileFrameImportant"/> tiles should try to match the the layout (FrameX and FrameY values) of the fallback tile so that the resulting tiles aren't broken.
`the the`, and it's `TileFrameX/Y` respectively

I'm thinking if the default being 0 could cause issues for exactly the reason outlined above. Maybe TML should handle  fallbacks differently based on `Main.tileFrameImportant`? A tileFrameImportant tile rn would fall back to 0 which would most certainly break stuff (if the original tile's frames are out of bounds of the 0 type sheet)

2025-05-15 22:10 UTC, JavidPack commented on patches/tModLoader/Terraria/ModLoader/ModBlockType.cs
> +	/// <br/><br/> <see cref="Main.tileFrameImportant"/> tiles should try to match the the layout (FrameX and FrameY values) of the fallback tile so that the resulting tiles aren't broken.
So, if a frameimportant tile falls back to a non-frameimportant tile, the resulting tiles will all be framed during the process so they'll fix themselves. Even though they had invalid frameXY values for a Dirt tile, during framing those will be fixed.

2025-05-21 23:53 UTC, merged