[WIP] ModAccessorySlot equipment loadouts support
bluemagic123/tModLoader pull request #4340
Opened 2024-08-09 09:40 UTC by alueck

### What is the new feature?
Equipment loadouts support for `ModAccessorySlot`

### Why should this be part of tModLoader?
Because modded accessory slots should support the vanilla equipment loadout switching

### Are there alternative designs?

### Sample usage for the new feature
No changes required if a mod just adds new acessory slots. Mods that add additional loadouts would need to do some changes though. But I want to discuss the design of this first. See notes below.

### Porting Notes

### Discussion
There are a few points I would like to discuss:
- The changes made in this PR are breaking changes in terms of behavior of modded accessory slots. If you are using e.g. a Wing Slot mod, the wing slot is currently shared between all equipment loadouts, which might actually be wanted by the modder or players. If this PR was merged, the wings that were previously shared between loadouts would just be equipped in loadout 1. How should this be handled?
- Should `ModAccessorySlot` get a property which indicates whether the accessory slot is shared between loadouts or loadout specific? Doing this could impose some other problems though. E.g. changing the value of the property from loadout specific to shared between loadouts would lead to the loss of items if there are multiple items equipped in different loadouts for this slot. This might be something modders could handle though.
- There are mods which add additional equipment loadouts. I designed the code so that it would also work with additional equipment loadouts but I am not quite sure if my approach is good enough. This is actually the first time I did anything with tModLoader / Terraria modding.
  - I added a method `AppendAdditionalEquipmentLoadout` to `ModAccessorySlotPlayer` which needs to be called once on initialization for each equipment loadout a mod adds. 
  - `ModAccessorySlotPlayer` has a property `ModdedCurrentLoadoutIndex` which needs to be set to the loadout index if the loadout was switched. I added a hook `OnEquipmentLoadoutSwitched` which `ModAccessorySlotPlayer` currently uses to set this property if the loadout was switched. Modders might have to implement some custom logic to set `ModdedCurrentLoadoutIndex` to the equipment loadout index corresponding to their loadout.

### TODOs
- Multiplayer needs testing

2024-08-09 16:20 UTC, direwolf420 commented
Over on the tmodloader discord there is a discussion ongoing about implementation details and use cases: https://discord.com/channels/103110554649894912/1148455439491682425 if you are interested

2025-05-12 21:18 UTC, Chicken-Bones requested changes

2025-05-12 21:18 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +		return functionalIssue || vanityIssue;
It would be good to disable the vanity and functional slots independently. I'm not sure how feasible that is.

2025-05-12 21:18 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/AccessorySlotLoader.cs
> +		itemCollection[slot + player.armor.Length] = new Item();
Might be worth caching this `Item` instance

2025-05-13 21:47 UTC, JavidPack commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +		return functionalIssue || vanityIssue;
I was able to implement this appraoch.

2025-05-14 01:31 UTC, Chicken-Bones requested changes

2025-05-14 01:31 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +	private readonly HashSet<int> sharedLoadoutSlotTypes = [];
Should still be an array.

2025-05-14 01:31 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +	private readonly Dictionary<string, (int SlotType, bool HasLoadoutSupport)> slots = [];
Looks like this `bool HasLoadoutSupport` is unused now.

2025-05-14 01:31 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +			if(!items.Accessory.IsAir)
Might be worth running an `(if|for|foreach)\(` to find missing spaces periodically

2025-05-14 01:31 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +			List<SlotInfo> result = [];
This should be `List<Item> itemsToDrop`. Modify the return type and `extraItems` accordingly

2025-05-14 01:31 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +			IList<bool> visible;
No need for forward declaration, just `var` below

2025-05-14 01:31 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +				bool hasLoadoutSupportSettingForSlotChanged = !hasLoadoutSupport && (!dye.IsAir || !accessory.IsAir || !vanityItem.IsAir);
Can simplify this with above ^. Just `if (!hasLoadoutSupport)` add each non-air item to `itemsToDrop`

2025-05-14 01:31 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +				bool isHidden = visible.ElementAtOrDefault(i);
Why are we using `ElementAtOrDefault`? Is there some way the data could be missing? Scary

2025-05-14 01:31 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +	internal sealed record SlotInfo
Correspondingly, this class will be unused

2025-05-19 18:30 UTC, JavidPack commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +	private readonly HashSet<int> sharedLoadoutSlotTypes = [];
Done.

2025-05-19 18:30 UTC, JavidPack commented on patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
> +	private readonly Dictionary<string, (int SlotType, bool HasLoadoutSupport)> slots = [];
Done.

2025-05-22 18:41 UTC, merged