Store Mod Hash Data in Developer Metadata
bluemagic123/tModLoader pull request #4345
Opened 2024-08-14 02:33 UTC by Solxanich

### What is the new feature?
To support investigations in to mods and verifying  authenticity, we would like to store ongoing hash data of .tmods published to tML Workshop. 

This PR implements the storage of Mod Hashes on to the Developer Metadata field. 
This PR also refactors the related ModDownloadItem processing method.

### Why should this be part of tModLoader?
Add the opportunity to validate authenticity of a tmod file.

### Are there alternative designs?
TBD

2024-08-15 03:11 UTC, Chicken-Bones requested changes
Good cleanup

2024-08-15 03:11 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
> +	}
```suggestion
	internal enum SearchResult
	{
		NotFound,
		SearchFailed,
		Success,
		RetrievalFailed,
	}
```

2024-08-15 03:11 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/SteamedWraps.cs
> +			SteamUGC.SetReturnMetadata(qHandle, true);
Do we want this always on? Will it affect our retrievable performance? Perhaps we should have a `QueryParameters` flag for it

2024-08-15 03:11 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
> +		}
Need to put the `JsonConvert` inside the loop. Unfortunately this doesn't fit `do-while` either, so you'll have to use 
```cs
while (true) {
    string devMetadata = JsonConvert
    if (devMetadata.Length <= Steamworks.Constants.k_cchDeveloperMetadataMax)
        break;
    
    StripOldHashes
}

2024-08-15 03:11 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
> +		}
No while loop here. Keep the code simple. We should just drop the oldest entry each time. Rather than 'reserving' items, we were just going to sort them so that the ones we most want to keep are at the top of the list.

2024-08-15 03:11 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
> +	}
This is a bit more complicated than what we discussed in Discord. I'm also not sure the ordering logic is correct. The list should contain the newest from each tML major version, followed by all the remaining versions from newest to oldest.

I thought the plan was to ignore browser versions, since we're not adding the workshop logic to those releases. When 1.4.5 comes, we'll still have plenty of months of overlap with 1.4.4 versions.

2025-09-02 01:49 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/SocialBrowserModule.cs
> +		modVersion = new Version(match.Groups[2].Value);
I thought we had agreed on not including versions in the hash list

2025-09-02 01:51 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
> +				}
This is fine for now, but the final download mods from servers feature will probably need to be extra serious about preventing the download of banned mods

2025-09-02 01:53 UTC, Chicken-Bones commented on SteamWebAPIPublisherTool/ModLoaderSimple/EntryReadStream.cs
> +internal sealed class EntryReadStream : Stream
Any reason you can't reference tML as a library?

2025-09-18 04:50 UTC, Chicken-Bones commented on SteamWebAPIPublisherTool/ModLoaderSimple/EntryReadStream.cs
> +internal sealed class EntryReadStream : Stream
Use https://github.com/tModLoader/tModLoader/pull/4731

2025-09-18 05:40 UTC, Chicken-Bones requested changes

2025-09-18 05:40 UTC, Chicken-Bones commented on SteamWebAPIPublisherTool/BatchMetadataSetRunner.cs
> +		Directory.Delete(actualWorkshopItemsFolder, deleteModsWhenComplete);
According to docs, this will throw if the directory is non empty and `deleteModsWhenComplete: false`

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/SocialBrowserModule.cs
> +		hash = Encoding.UTF8.GetString(modFile.Hash);
I thought we were going to use `Convert.ToBase64String`. `TmodFile.Hash` is a full `byte[20]` not text encoded.

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/SocialBrowserModule.cs
> +	private string hash; // 28+2 chars, SHA1. +2 is for string type
comment accuracy? What's 'string type' here (I forget)

2025-09-18 05:40 UTC, Chicken-Bones commented on SteamWebAPIPublisherTool/SteamWebAPIPublisherTool.csproj
> +</Project>
I think this project belongs subfoldered in `extras`

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/UI/ModBrowser/ModDownloadItem.cs
> +	public ModDownloadItem(string displayName, string name, Version version, string author, string modReferences, ModSide modSide, string modIconUrl, string publishId, int downloads, int hot, DateTime t
Remove `Banned` argument, should always be false for this constructor

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/UI/ModBrowser/ModDownloadItem.cs
> +	internal ModDownloadItem(string displayName, string publishId, bool banned = true)
Remove default value for `banned` arg. Ideally we'd make this `ctor` and have a clearly named factory method, but `new ModDownloadItem(e.displayName, e.modPubId, banned: true)` works perfectly fine as you have it

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/UI/ModBrowser/ModDownloadItem.cs
> +		var devMetadata = JsonConvert.DeserializeObject<DeveloperMetadata>(DevMetadata);
is it worth doing some future proofing by having the `DevMetadata` be a json object at root, and having the `hashes` list be a field? If we are concerned about the limit we could also just have the hashes be a single string with a separator like `|`.

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
> +	private static readonly Regex MetadataInDescriptionFallbackRegex = new Regex(@"Version Summary: ", RegexOptions.Compiled);
why is this changing?

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
> +									throw new BannedModException($"The mod {item.DisplayName} with ID {item.PublishId} is Banned!", item.DisplayName, item.PublishId.ToString());
The `message` here should probably be generated inside the `BannedModException` class, and should probably be localized. Also no need for braces for single line guard `if`

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
> +
Is throwing an exception going to cause problems if the query accidentally matches a banned mod? This method previously didn't throw. Is this one of the cases where a mod should actually be skipped if banned, or is it a case where an item should be returned with `Banned: true`? Needs caller analysis.

In addition, the comment at the top of this method says
```
			/// Note that the List size is 1 to 1 with the provided array.
			/// If the Mod is not found, the space is filled with a null.
```

Which appears to be outdated, probably from when we added the `out List<string> missingMods`

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
> +					if (state != WorkshopSearchReturnState.Success)
skipps banned items, lgtm :)

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
> +						throw new BannedModException($"The mod {item.DisplayName} with ID {item.PublishId} is Banned!", item.DisplayName, item.PublishId.ToString());
Similarly, to above, is it okay to throw here now?

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
> +					throw new BannedModException($"Item {id}: '{displayname}' is banned. Skipping...", displayname, id.ToString());
No need to say `Skipping...`, in fact it's not really this method's job to say what's going to happen with the exception when it's handled

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
> +		if (BuildInfo.IsDev && modFile.Name != "ToBeDeleted") {
leftover test code?

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
> +		if (state == WorkshopHelper.WorkshopSearchReturnState.RetrievalFailed) {
the condition above already guards this one

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
> +			tModFile.Open(); // Needed for Hash data to be populated
`using var _ = tModFile.Open();` since it returns an `IDisposable` handle

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
> +		var overflowLength = JsonConvert.SerializeObject(devMetadata).Length - MaxMetadataLength;
We should probably use serializer params that remove any unnecessary whitespace.

2025-09-18 05:40 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
> +		var minNumberOfHashes = 2 * SocialBrowserModule.keepRequirements.Select(a => a.keepCount).Sum();
Surely this whole function could be simpler if we just ran a while loop and dropped the oldest hash and reserialized. There's only ever going to be a small handful of hashes to drop, and serialization takes a negligible amount of time. 

We can check that the number of hashes we kept at the end is at least the number in the current upload for your exception below

2025-09-22 01:58 UTC, Chicken-Bones requested changes

2025-09-22 01:58 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +		return System.Text.Json.JsonSerializer.Serialize(this);
Lets stick to Newtonsoft.Json, since that's what we use elsewhere in tML.

2025-09-22 01:58 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +		hash = Encoding.UTF32.GetString(modFile.Hash);
As mentioned on Discord, we want to make sure we use `Convert.ToBase64`

2025-09-22 01:58 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +	private string hash;
We want to make sure that json serializes this as a string, and not as an object with a `hash` field `{ hash: "..." }`

2025-09-23 07:09 UTC, Chicken-Bones requested changes

2025-09-23 07:09 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/UI/Interface.cs
> +							throw new BannedModException($"The missing dependency {item.DisplayName} is Banned on Workshop.", item.DisplayName, item.PublishId.ToString());
Tested, throwing at this point causes the game to hard crash, probably sufficient to just log error and skip

2025-09-23 07:09 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/UI/Interface.cs
>  							Logging.tML.Error($"Could not find removed mod on Workshop: {slug}");
might as well pass the `state` through to the log message. Lil more info

2025-09-23 07:09 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +	}
Better practice is to move the error handling to the `Deserialize` factory method. You can put `string.IsNullOrEmpty` check in there, as well as return a 'default' metadata on error

2025-09-23 07:09 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +	internal DeveloperMetadata(string workshopPath, bool useWebApi, ModDownloadItem modDownloadItemAsFound = null)
Similar to my below comment, this would be better as a factory method. It 'does too much work' to be considered a constructor. At a start, I'd consider making `CalculateModHashes` return a `DeveloperMetadata`

2025-09-23 07:09 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +	private void CalculateModHashes(string workshopPath, bool useWebApi, ModDownloadItem modDownloadItemAsFound = null)
In addition, you have an invariant where `useWebApi` is `true` if and only if `modDownloadItemAsFound == null`, so as a start, remove the `useWebApi` and document that if no `modDownloadItemAsFound ` is provided, the item will be obtained from the workshop.

Better yet, this function seems to be taking on too much responsibility, and in the principle of making parameters to functions as narrow and minimal as possible, instead of passing in an entire `ModDownloadItem` we should just pass in a `DeveloperMetadata` and leave the job of getting the metadata from workshop or mod download item to the call sites (of which there is only one of each)

2025-09-23 07:09 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +	private void TrimDevMetadata()
seems my previous comment got lost. Instead of this complicated logic, I recommend just running `GetSerialize()` in a `while` loop and dropping the last hash on length overflow. This could run at the end of `CalculateModHashes`

2025-09-23 07:09 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +	internal static DeveloperMetadata DeSerialize(string serializedDevMetadata)
`Deserialize` is one word, as seen in the json call below

2025-09-23 07:09 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +	internal string GetSerialize()
just `Serialize` is good

2025-09-23 07:09 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopBrowserModule.cs
> +			throw new BannedModException($"Attempted to Download a Banned Mod {item.DisplayName} with ID {item.PublishId}. Aborting...", item.DisplayName, item.PublishId.ToString());
Good place for this guard. Tested that the exception shows a UI. Found that `PublishId` was missing a `ToString` in the process

2025-09-23 07:09 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
> +	private ModDownloadItem modDownloadItemAsFound;
Scary! Please store `DevMetadata` on `FoundWorkshopEntryInfo` or add it as another `out` param in `TryGetInfoForMod`. Then pass it through to `PublishMod` as a field in `WorkshopItemPublishSettings` (such as `ExistingMetadata`

2025-09-24 05:57 UTC, Chicken-Bones requested changes
Looking pretty good

2025-09-24 05:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/LocalMod.cs
> +	internal static LocalMod OpenModFile(string path)
call it `FromWorkshopModFile` and we're good

2025-09-24 05:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/ModOrganizer.cs
> +	internal static List<ModVersionHash> GetModHashesFromFolder(string folderPath)
I think this was better in `WorkshopSocialModule`, I don't see this function being relevant for the general operation of mod loading and launching

2025-09-24 05:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
>  			if (devMetadata == null || devMetadata.modVersionHashes == null) {
do we really need this guard? I'm not sure how it would be possible to hit this condition.

2025-09-24 05:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +			return default;
Shouldn't we return `new()` like above?

2025-09-24 05:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopBrowserModule.cs
> +		return items.First().DevMetadata;
Can do `items.FirstOrDefault()?.DevMetadata ?? new()` if you feel like being fancy

2025-09-24 05:57 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
> +		return newDeveloperMetadata;
This code will need maintenance if we ever add anything new to developer metadata that isn't recalculated each time in this function. I think it would be better if we just did something like

```cs
var developerMetadata = WorkshopBrowserModule.Instance.GetDeveloperMetadataFromModBrowser(pubId);
developerMetadata.modVersionHashes = currentHashes.Concat(developerMetadata.modVersionHashes.Except(currentHashes).ToList()).ToList();
developerMetadata .TrimDevMetadataForPublish();
return developerMetadata;
```

I think `GetDeveloperMetadataFromModBrowser` will return an empty metadata for 0 publishid, but if not, we can `: new()` it

2025-09-27 03:18 UTC, Solxanich commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
>  			if (devMetadata == null || devMetadata.modVersionHashes == null) {
Yeah, that's an artifact of System.Text.Json which return null instead of throwing; removed.

2025-09-29 23:22 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Social/Base/DeveloperMetadata.cs
> +using System.Runtime.Intrinsics.Arm;
Remove this line. Approved

2025-09-29 23:33 UTC, merged