Added Player.breathEffectiveness to facilitate "extends underwater breathing"
bluemagic123/tModLoader pull request #4399
Opened 2024-10-03 20:22 UTC by JavidPack

Modders currently adjust `Player.breath` to fake an effect similar to diving helmet. https://github.com/tModLoader/tModLoader/commit/0d55bc751d5b2b7c5fabb5ea5e3a028a2215283a fixed some issues with doing that for current modders, but complete support would allow for better control.

Currently, adjusting `Player.breath` can linearly lengthen underwater breathing time, but the effect isn't numerically equivalent to vanilla approaches. Vanilla approaches are multiplicative, which currently isn't possible to do correctly due to mod execution order. Also, adjusting `Player.breath` past 400 results in a 2nd row of bubbles that keeps extending, which is not ideal.

This PR adds `Player.breathEffectiveness` as a `StatModifier`, allowing for base/additive/multiplicative adjustments to breathing time without adjusting `Player.breath`, which would be incompatible with multiple mods doing conflicting effects.

As a result, `Player.breath` now represents a breath capacity, while `Player.breathEffectiveness` represents a breath efficiency. Combined this should allow for, modders to individually adjust both. For example, a race with low breath capacity, an accessory doubling breathing efficiency, and an accessory increasing breathing capacity should all work together correctly no matter the load order.

For most modders, they'll want to switch from adjusting `Player.breath` to adjusting `Player.breathEffectiveness` instead for compatibility and avoiding the strange bubble indicator issue.

Sample usages:
```
		public override void UpdateAccessory(Player player, bool hideVisual) {
			player.breathMax += 200; // double breath capacity.
			player.breathEffectiveness += .5f; // Increase breath efficiency by 50%, additively.
```

2024-12-20 14:13 UTC, TacoConKvass commented
Can we get this anytime soon?

2025-02-05 01:11 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Player.TML.cs
> +
Needs docs. Explain that an effectiveness of 2 means breath lasts twice as long. Recommend modders use additive? 

Is there something without the Base/Flat?

2025-02-05 21:21 UTC, JavidPack commented on patches/tModLoader/Terraria/Player.TML.cs
> +
Vanilla is all multiplicative, but that can get out of hand pretty quickly I imagine. I'm not seeing a class like StatModifier without base/flat. We have AddableFloat and MultipliableFloat classes.

2025-04-17 15:34 UTC, direwolf420 commented
I'm curious, what's preventing this from being merged?

2025-04-28 23:48 UTC, Chicken-Bones requested changes

2025-04-28 23:48 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Player.cs.patch
>  +	/// <summary> How long it takes for <see cref="breathCD"/> to cause <see cref="breath"/> to decrease by 1. Defaults to 7 and is increased by factors such as holding a Breathing Reed, which doubles
Change doc to simply say, `How long it takes for <see cref="breathCD"/> to cause <see cref="breath"/> to decrease by 1. Defaults to 7 before <see cref="breathEffectiveness"/> is applied`

2025-04-28 23:48 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Player.TML.cs
> +
Okay, I'm happy with `StatModifier`. Please mention that this is applied in the calculation of `breathCDMax`

2025-04-28 23:48 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Player.cs.patch
>   				num *= 2;
Should we make breathing reed additive?

2025-04-29 19:51 UTC, JavidPack commented on patches/tModLoader/Terraria/Player.cs.patch
>   				num *= 2;
Done

2025-04-30 01:49 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Player.TML.cs
> +	/// How effectively the player can hold their breath underwater. Controls how long it takes for <see cref="breath"/> to decrease. Breathing Rod doubles this value and Diving Gear multiplies it by 6.
`Breathing Reed adds 1`

2025-04-30 22:47 UTC, merged