Refactor dedicated server management script and docker container
bluemagic123/tModLoader pull request #4484
Opened 2024-12-20 08:01 UTC by turtletowerz

closes #2650 

There were quite a few areas where the previous versions of the script and container fell short, notably:
* Symlinks hacks to get the Docker container to work with the old system of symlinking
* The base steamcmd/steamcmd docker image had steamcmd installed twice, adding ~30% to the image size
* There was no easy way to run commands or attach to the Docker Container
* Simarily, an entrypoint script to was added catch SIGTERM and gracefully shutdown to prevent previous data loss issues
* The regular management script (not Docker) had problems with the backup system
* Documentation was not very clear and led to some confusion; Various Discord forum posts were already answered in the docs. 

There was also some smaller fixes and general code cleanup to increase the overall quality.

Once this is merged the [wiki page for servers](https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server) will be updated with the new information

2025-01-08 02:26 UTC, scmarlatt commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/docker-compose.yml
> +      - ./tModLoader:/data
I came across an issue on macOS Sierra 15.1 and had to specify `platform: linux/amd64`

2025-01-08 02:27 UTC, scmarlatt commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/docker-compose.yml
> +      #   GID: 1000
Again, might be macOS specific, but when trying to build the container, it said the values I obtained from running `id` were already in use.

Just passing 1000/1000 seemed to allow the build to progress though

2025-01-08 02:28 UTC, scmarlatt commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/docker-compose.yml
> +      #   GID: 1000
Again, might be macOS specific, but when trying to build the container, it said the values I obtained from running id were already in use.

Just passing 1000/1000 seemed to allow the build to progress though

2025-01-30 02:23 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/README.md
> +* `world` sets the exact path to an existing or new terraria world, ex. `worldpath/to/your/world.wld`. **For Docker installations**, the world path must follow `/data/Worlds/your_world.wld`
Hmm, the fact that it's randomly `/data` inside the container is a bit painful. It'd be nice if paths inside weren't so unguessable/invisible. Can it be `tModLoader/Worlds/your_world.wld`?

2025-01-30 02:26 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/Dockerfile
> +EOF
Why do these scripts need to be part of the container? Can't people use tmux outside the docker run command? This creates a layer of complexity and separation between users of the management script and docker users

2025-01-30 02:38 UTC, Chicken-Bones requested changes
Concerned about breaking changes. Needs user testing.

2025-01-30 02:38 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> +	curl -s -O "$script_url" || exit 1
Why change this?

2025-01-30 02:38 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> -		mkdir -p Mods Worlds logs
Where go logs?

2025-01-30 02:38 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> + --tmlversion        Version of tModLoader to install. Only works if --github is provided. Functionally equivalent to the TMLVERSION env variable
Should probably keep the legacy arg as well, no need to break things unnecessarily

2025-01-30 02:38 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> -update_script
no auto update checker?

2025-01-30 02:38 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> +		--tmlversion)
Why this not set `--github` anymore? breaking change?

2025-01-30 02:38 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> -		fi
Where did this go?

2025-01-30 02:38 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/LaunchUtils/ScriptCaller.sh
> +. ./DotNetVersion.sh
Why?

2025-01-30 02:38 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> +		export SKIP_DOTNET_LOGCHECK=1
shouldn't this be docker only?

2025-01-31 19:58 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/README.md
> +* `world` sets the exact path to an existing or new terraria world, ex. `worldpath/to/your/world.wld`. **For Docker installations**, the world path must follow `/data/Worlds/your_world.wld`
Agreed, I've committed a small change to fix `/data` to `/tModLoader`

2025-01-31 20:02 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/Dockerfile
> +EOF
tmux makes it significantly easier for graceful Docker shutdowns. I had some issues in the past with tModLoader not shutting down gracefully in Docker and this was the simplest solution. I can do more testing to see if there's a way to solve this.

Additionally adding tmux allows for users to do one-off commands without having to enter the container.

For example: `docker exec -it tml execute "say Hello World!"` instead of having to `docker attach tml` and then type `say Hello World!" in the console.

2025-01-31 20:05 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> +	curl -s -O "$script_url" || exit 1
A misunderstanding on how `curl` deals with duplicate names. I've reverted my commit for this line, but I still think it's better to keep the curl output with `|| exit 1` as we should not ignore if there's an issue when downloading management script updates

2025-01-31 20:06 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> -		mkdir -p Mods Worlds logs
For non-Docker setups the logs will be in `server/tModLoader-Logs` as it is with any normal installation. Do you think I should symlink them so that `./logs -> ./server/tModLoader-Logs`?

2025-01-31 20:09 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> + --tmlversion        Version of tModLoader to install. Only works if --github is provided. Functionally equivalent to the TMLVERSION env variable
Brought back `--tml-version` to keep compatibility. All the other flags are the same I just changed the flag descriptions

2025-01-31 20:10 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> -update_script
It was moved below flag parsing so that doing something like `-h` or `-v` would not prompt for an update since there's no need in that case.

2025-01-31 20:11 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> -		fi
For docker it was moved to be a bind mount, so in `docker-compose.yml`

2025-01-31 20:14 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> +		--tmlversion)
Must've accidentally missed that, I have brought it back

2025-01-31 20:17 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/LaunchUtils/ScriptCaller.sh
> +. ./DotNetVersion.sh
`source` and `.` are functionally equivalent in bash and `.` is used elsewhere in the same script so I changed it to match

2025-01-31 20:23 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> +		export SKIP_DOTNET_LOGCHECK=1
No, this is an issue with any install from Github. One solution I had as a temporary fix was to create `server.log` and `client.log` manually during the `install-tml` phase but I don't really like the idea of creating log files before anything is actually logged. If you think I should do this instead of `SKIP_DOTNET_LOGCHECK` then I can change that

2025-01-31 23:29 UTC, turtletowerz commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/docker-compose.yml
> +      - ./tModLoader:/data
Added platform as an option, but noted that there ARM is not functional currently

2025-03-17 23:50 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> +		export SKIP_DOTNET_LOGCHECK=1
Yeah, lets generate a `server.log` of `dotnet installed via management script... pending first server start...`

2025-03-17 23:51 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/LaunchUtils/ScriptCaller.sh
> +. ./DotNetVersion.sh
Lets revert changes to this file, I've suggested a log solution above

2025-04-16 01:14 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/README.md
> +   * Run . No mods will be installed if `install.txt` is missing, and no mods will be enabled if `enabled.json` is missing. **You will need a `Mods/enabled.json` to contain all Mods that you want ena
Run?

2025-06-23 21:52 UTC, JavidPack commented
I noticed the readme doesn't really say how to get manage-tModLoaderServer.sh on the computer, I think it might be helpful to add curl/wget instructions on how to download the file directly. Some may not know how to copy files over to their server if they don't have a gui.

2025-11-17 05:04 UTC, Chicken-Bones approved these changes
Approved pending user testing

2026-03-26 01:21 UTC, merged

2026-06-29 17:48 UTC, oksoff commented on patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh
> +			mkdir -p "$folder/Mods" "$folder/Worlds"
This should've been
```suggestion
			mkdir -p "Mods" "Worlds"
```
Since we're already in `$folder` from :347

It's only a problem if `folder` is defined though.

EDIT: or rather it's a problem if `folder` is not an absolute path.