Hard coded text within standardized ExampleMod
bluemagic123/tModLoader pull request #4487
Opened 2024-12-22 21:51 UTC by hezuo1hao

### What are the changes to ExampleMod?
I have modified all the hard coded text, and now all of these hard coded texts have been stored in the localization file

### Do these changes need additional documentation?
No

2025-02-05 02:52 UTC, Chicken-Bones requested changes
Lots of fantastic changes and good examples here. Please read my comments from bottom to top as that's the order I reviewed the PR in (starting with the localization file).

Main request is to just leave a few things unlocalized.
- Exceptions/errors which only show in logs
- Messages which are referring to specific fields/methods or other code terminology, to be read by developers. Commonly in style showcase items.

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/Localization/en-US.hjson
> +			}
Recommend deduplicating some of these error messages. A simple `"{0} is not a valid number"` especially since the code doesn't actually check world bounds or any such. Maybe put them under `Commands.ErrorMessages.XXX`

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/ExampleMod.Networking.cs
> +		public static LocalizedText LoggerText { get; private set; }
We don't use localizations in logs as they're not player facing, and can make it harder for the developers to diagnose issues

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/ExampleMod.ModCalls.cs
> +		public static LocalizedText[] ErrorText { get; private set; }
Exception messages are only shown in logs, and shouldn't be localized.

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/ExampleMod.ModCalls.cs
> +				throw new ArgumentNullException(ErrorText[0].Format(nameof(args)));
Honestly, `ArgumentNullException(nameof(args))` is plenty here, the text was unnecessary to start with.

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/Content/Tiles/TileObjectDataShowcase.cs
> +			Main.NewText(DataText.Format(style, tileData.Style, alternatePlacement - tileData.Style, alternatePlacement, style * tileData.StyleMultiplier + alternatePlacement, direction, alternate, tileData.O
I think localizing this detracts from the ease of reading the example. This example is intended for developers to better understand the code, so it's important to use the same language as the documentation

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/Content/NPCs/ExampleBoneMerchant.cs
>  				// You can also use localization keys (see Localization/en-US.lang)
Remove this comment line, since localization is no longer optional

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/Content/Items/Weapons/HitModifiersShowcase.cs
> +			ModeText = [this.GetLocalization("Mode_0"),
`Enumerable.Range(0, 8).Select(i => this.GetLocalization($"Mode_{i}")).ToArray();`

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/Content/Items/CustomItemDrawingShowcase.cs
> +			tooltips.Add(new TooltipLine(Mod, "DrawModeDetails", DrawModeDetailsText.Format(drawMode, GetMessageForDrawMode())));
Since this is another item for teaching developers, I think it reads better unlocalized

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/Content/BuilderToggles/FreeBaitBuilderToggle.cs
> +			_ => UnknownText.Value
Since this is a programming error message, it doesn't need localization

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/Common/UI/ExampleCoinsUI/ExampleCoinsUISystem.cs
> +		exampleCoinUserInterface = new UserInterface();
Unintentional change?

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/Common/Players/ExampleArmorSetBonusPlayer.cs
> +			Main.NewText(CurrentShadowStyleText.Format(styleName));
Nothing to localize here. These are developer messages

2025-02-05 02:52 UTC, Chicken-Bones commented on ExampleMod/Common/GlobalProjectiles/ExampleProjectileModifications.cs
> +		public static LocalizedText TimesHitOnThirdHitText { get; private set; }
Just call it `HitMessage`

2025-02-27 08:06 UTC, hezuo1hao commented on ExampleMod/Common/UI/ExampleCoinsUI/ExampleCoinsUISystem.cs
> +		exampleCoinUserInterface = new UserInterface();
> Unintentional change?

Unfortunately, in order for localization to load properly, the instantiation timing of the UI needs to be slightly shifted back

2025-02-27 08:08 UTC, hezuo1hao commented on ExampleMod/Content/Items/CustomItemDrawingShowcase.cs
> +			tooltips.Add(new TooltipLine(Mod, "DrawModeDetails", DrawModeDetailsText.Format(drawMode, GetMessageForDrawMode())));
> Since this is another item for teaching developers, I think it reads better unlocalized

Can we consider placing the original version as a comment above, which would be both easy to read and localized within the game

2025-02-27 08:11 UTC, hezuo1hao commented on ExampleMod/Content/Tiles/TileObjectDataShowcase.cs
> +			Main.NewText(DataText.Format(style, tileData.Style, alternatePlacement - tileData.Style, alternatePlacement, style * tileData.StyleMultiplier + alternatePlacement, direction, alternate, tileData.O
> I think localizing this detracts from the ease of reading the example. This example is intended for developers to better understand the code, so it's important to use the same language as the documentation

Can we consider placing the original version as a comment above, which would be both easy to read and localized within the game

2025-02-27 08:35 UTC, hezuo1hao commented
Okay, I will make the modifications according to the annotations

2025-02-28 00:22 UTC, Chicken-Bones commented on ExampleMod/Content/Tiles/TileObjectDataShowcase.cs
> +			Main.NewText(DataText.Format(style, tileData.Style, alternatePlacement - tileData.Style, alternatePlacement, style * tileData.StyleMultiplier + alternatePlacement, direction, alternate, tileData.O
Sorry, I think you misunderstand me. We want to keep the example really simple, because it's not meant to be copied and edited, instead, it's meant to teach about `TileObjectData`. Localization detracts from this a bit.

2025-02-28 08:46 UTC, hezuo1hao commented on ExampleMod/Content/Tiles/TileObjectDataShowcase.cs
> +			Main.NewText(DataText.Format(style, tileData.Style, alternatePlacement - tileData.Style, alternatePlacement, style * tileData.StyleMultiplier + alternatePlacement, direction, alternate, tileData.O
> Sorry, I think you misunderstand me. We want to keep the example really simple, because it's not meant to be copied and edited, instead, it's meant to teach about `TileObjectData`. Localization detracts from this a bit.

Okay, I understand. I'll go make some changes

2025-03-04 05:54 UTC, merged