feat: postpone hash verification until read error or mod load
bluemagic123/tModLoader pull request #4492
Opened 2024-12-30 20:42 UTC by steviegt6

### What is the new feature?

`.tmod` file loading as been adjusted to only verify data blob lengths rather than full hash verification. Instead, hash verification has been postponed to mod loading to minimize unnecessary hashing. Hashes will also be taken if the initial `TmodFile::Read` invocation fails.

### Why should this be part of tModLoader?

It significantly speeds up start-up times.

### Are there alternative designs?

A better hashing algorithm and streaming in the background is possible but unnecessary (the former) and terrible (the latter).

2024-12-30 20:49 UTC, Mirsario approved these changes

2024-12-30 20:51 UTC, steviegt6 commented
As a side note: I'm personally of the opinion we should remove hashing entirely. Data corruption of this nature is rare and most mods are now sourced from the Steam workshop, which should verify file integrity itself anyway. Many other mod loaders (such as various Minecraft ones) don't hash and face no issues.

It really seems to exist as a remnant of early tModLoader (the entire `.tmod` file format does, for that matter) with little consideration for its continued existence in the current day. For compatibility reasons, we could continue to supply a hash but just skip checking entirely.

2024-12-31 11:19 UTC, Chicken-Bones requested changes
Overall seems sensible, just some implementation feedback

2024-12-31 11:19 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/TmodFile.cs
> +	private bool hashMatches;
`bool? hashVerified`

2024-12-31 11:19 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/TmodFile.cs
> +	private static readonly SHA1 sha1 = SHA1.Create();
Does this actually make a difference to performance? We're not multithreading right now, but it's a reduction in encapsulation and potential for future mistakes.

2024-12-31 11:19 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/TmodFile.cs
> +			handle = Open();
No need for the `if` check here. You need to use `using`. The guard statements should also run before trying to get a file handle.

2024-12-31 11:19 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/TmodFile.cs
> +		fileStream.Position = oldPos;
No need to put `Position` back, but you should assert that `sharedEntryReadStream == null` just like in `GetStream`. Or just open a new `FileStream`, I don't think there's any real benefit to reusing the existing one for this.

2024-12-31 11:19 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/TmodFile.cs
> +	internal bool VerifyHash()
Should probably be something like `VerifyHash() => hashVerified ??= _VerifyHash()` where `_VerifyHash` has the impl and is `private`.

2024-12-31 11:23 UTC, Chicken-Bones commented
> As a side note: I'm personally of the opinion we should remove hashing entirely. Data corruption of this nature is rare and most mods are now sourced from the Steam workshop, which should verify file integrity itself anyway. Many other mod loaders (such as various Minecraft ones) don't hash and face no issues.
> 
> It really seems to exist as a remnant of early tModLoader (the entire `.tmod` file format does, for that matter) with little consideration for its continued existence in the current day. For compatibility reasons, we could continue to supply a hash but just skip checking entirely.

Other mod loaders do hash during the data retrieval process. While I agree that data corruption is rare, and the mod would most likely fail to load if it occurred, I don't entirely trust steam our our own server-client mod syncing. In the past hashing was more important because of the signing and trust chain, but I'd like to keep it if the performance impact can be acceptably mitigated.

2025-01-02 01:36 UTC, hakusaro approved these changes

2025-01-02 22:46 UTC, steviegt6 commented on patches/tModLoader/Terraria/ModLoader/Core/TmodFile.cs
> +			handle = Open();
You're right: when I was glancing at the implementation of Open I misunderstood the `fileStream != null` check.

2025-01-02 22:53 UTC, steviegt6 commented on patches/tModLoader/Terraria/ModLoader/Core/TmodFile.cs
> +	private static readonly SHA1 sha1 = SHA1.Create();
It does not and I didn't explicitly intend to leave that in there. The multithreading issues are a good catch.

2025-01-03 01:27 UTC, Chicken-Bones requested changes
Looking good! Just minor cleanups

2025-01-03 01:27 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/TmodFile.cs
> +			throw new IOException($"File not open: {path}", exception);
No need for this anymore

2025-01-03 01:27 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/Core/TmodFile.cs
> +			throw new Exception(Language.GetTextValue("tModLoader.LoadErrorHashMismatchCorrupted"), exception);
May as well inline this, since the method has no other uses. Then you probably don't need the assert.

2025-01-03 02:33 UTC, merged

2025-01-05 03:56 UTC, Chicken-Bones commented
[2024.12.2.1](https://github.com/tModLoader/tModLoader/releases/tag/v2024.12.2.1) now on preview