Added extra hooks representing ActuateForced
bluemagic123/tModLoader pull request #931
Opened 2020-05-22 19:26 UTC by OliHeamon

### What is the new feature?
Hooks for `ModTile`s/`GlobalTile`s that allow control over whether or not specific types of tile can be actuated. Also includes a second hook, `CanActuateForcibly`, so that modders can choose whether they want to also prevent their tiles from being force actuated using WorldGen, etc.

### Why should this be part of tModLoader?
Currently, the only way of achieving this is through a Runtime Detour, and adding the feature to tML will make it easier for more modders to grasp. Additionally, it may be useful for modders wishing to create more sophisticated structures that cannot be actuated into, reminiscent of the Jungle Temple.

### Possible drawbacks
N/A

### Applicable Issues
N/A

2020-05-23 08:56 UTC, Jofairden commented
You could've just left the other PR open, but okay.

2020-05-23 09:00 UTC, Jofairden requested changes

2020-05-23 09:00 UTC, Jofairden commented on patches/tModLoader/Terraria/Wiring.cs.patch
> ++			if (!tile.actuator() || !TileLoader.CanActuate(tile))
Shouldn't CanActuate override tile.actuator? I thought the intention was to provide the possibly for actuation without vanilla logic.

2020-05-23 11:56 UTC, OliHeamon commented on ExampleMod/ExampleMod.csproj
> +  </ItemGroup>
Oops, will remove this.

2020-06-05 10:44 UTC, Jofairden requested changes
Good, you fixed almost all of it. See comment.

2020-06-05 10:44 UTC, Jofairden commented on patches/tModLoader/Terraria/Wiring.cs.patch
> ++			if (!TileLoader.CanActuate(tile) || !tile.actuator())
Isn't this still wrong, wasn't your intent to override vanilla? You'd need different logic:
```suggestion
+			if (!TileLoader.CanActuate(tile) && !tile.actuator())
```

2021-03-07 17:04 UTC, Solxanich commented
Hello @OliHeamon  ; thank you for drafting this PR.
As the tModLoader project continues to progress, I'd like to ask if you intend to return to complete this PR and address Jofairden's review comments?

If not, could you please let us know, so we can have someone else pick up the branch and bring it to completion?

Thank you for your time.

2022-01-05 13:14 UTC, closed without merging